title: Faith Jeptoo
description: Data Analyst | Data Scientist | Designer | Social Media Manager
theme: jekyll-theme-minimal  
show_downloads: true  

author:
  name: Faith Jeptoo
  email: Jeptoofaithkibowen@gmail.com
  github: kibowenfaith

ALX Data Analytics: https://intranet.alxswe.com/certificates/8Nxh6TLpRE
Data Science & AI Adanian Labs and KCB Foundation : https://kcb-foundation.aiceafrica.com/396438
